/** StudentFlow | 학기 운영 보드: 실제 학교 맥락의 고르지 않은 샘플 데이터 */
import type { Announcement, Archive, AttendanceRecord, EventItem, Meeting, Notice, Task, Team, User } from "@/types";
export const roles = { MEMBER: "임원", DEPARTMENT_HEAD: "부장", EXECUTIVE_BOARD: "회장단", TEACHER: "담당 선생님" } as const;
export const users: User[] = [
  { id: "u1", name: "김서윤", role: "MEMBER", department: "홍보부", grade: "2학년 3반", initials: "서" }, { id: "u2", name: "이도현", role: "DEPARTMENT_HEAD", department: "기획부", grade: "3학년 1반", initials: "도" }, { id: "u3", name: "박지후", role: "EXECUTIVE_BOARD", department: "회장단", grade: "3학년 3반", initials: "지" }, { id: "u4", name: "한미정", role: "TEACHER", department: "학생자치 담당", grade: "교사", initials: "한" }, { id: "u5", name: "정민재", role: "MEMBER", department: "체육부", grade: "2학년 5반", initials: "민" }, { id: "u6", name: "최하린", role: "MEMBER", department: "생활안전부", grade: "1학년 4반", initials: "하" }, { id: "u7", name: "윤가람", role: "MEMBER", department: "기획부", grade: "2학년 1반", initials: "가" }, { id: "u8", name: "오준서", role: "MEMBER", department: "홍보부", grade: "1학년 2반", initials: "준" },
];
const legacyTasks: Array<Omit<Task, "type">> = [
  { id: "t1", title: "학교 축제 부스 운영표 확인", description: "우리 반 체험 부스의 운영 시간과 담당자를 확인한 뒤, 빈 시간대를 표시해 주세요. 변경이 있으면 운영표 파일에 직접 메모해도 됩니다.", department: "기획부", assigneeId: "u1", dueDate: "2026-08-15 17:00", priority: "높음", status: "TODO", submitted: false, attachmentHint: "축제_부스운영표_초안.xlsx" },
  { id: "t2", title: "아침 방송 원고 제출", description: "8월 넷째 주 아침 방송용 원고입니다. 안내 사항과 날씨 멘트를 포함해 1분 30초 안으로 작성해 주세요.", department: "홍보부", assigneeId: "u1", dueDate: "2026-08-16 12:00", priority: "높음", status: "IN_PROGRESS", submitted: false },
  { id: "t3", title: "체육대회 응원 도구 수량 조사", description: "반별 응원 막대와 색지 재고를 세고, 부족한 수량을 수량 조사표에 적어 주세요.", department: "체육부", assigneeId: "u5", dueDate: "2026-08-19 15:30", priority: "보통", status: "DONE", submitted: true },
  { id: "t4", title: "급식실 질서 캠페인 문구 정리", description: "점심시간 안내 문구 3개를 짧고 자연스럽게 정리해 주세요.", department: "생활안전부", assigneeId: "u6", dueDate: "2026-08-21 16:00", priority: "보통", status: "TODO", submitted: false },
  { id: "t5", title: "축제 포스터 게시 위치 확인", description: "각 층 게시판의 빈 공간과 게시 가능 날짜를 사진으로 남겨 주세요.", department: "홍보부", assigneeId: "u8", dueDate: "2026-08-18 13:20", priority: "보통", status: "TODO", submitted: false },
  { id: "t6", title: "2학기 학생회 예산안 1차 확인", description: "부서별 요청 금액과 영수증 처리 기준을 확인합니다.", department: "회장단", assigneeId: "u3", dueDate: "2026-08-14 18:00", priority: "높음", status: "IN_PROGRESS", submitted: false },
  { id: "t7", title: "학생회실 물품 정리 사진 업로드", description: "정리 전후 사진을 올리고, 버릴 물품은 따로 표시해 주세요.", department: "기획부", assigneeId: "u7", dueDate: "2026-08-13 16:00", priority: "낮음", status: "DONE", submitted: true },
  { id: "t8", title: "점심시간 교내 방송 장비 점검", description: "마이크 2개, 앰프, 연결 케이블 작동 여부를 확인합니다.", department: "홍보부", assigneeId: "u1", dueDate: "2026-08-22 11:30", priority: "낮음", status: "TODO", submitted: false },
];
export const tasks: Task[] = legacyTasks.map(task => ({ ...task, type: "SIMPLE" }));
export const events: EventItem[] = [
  { id: "e1", title: "2026 학생회 여름 워크숍", date: "8월 20일 (목)", time: "13:30–16:30", location: "시청각실", department: "전체 학생회", description: "2학기 행사 운영 방식과 부서별 역할을 확인하는 워크숍입니다. 시작 10분 전까지 출석해 주세요.", capacity: 32, participants: ["김서윤", "이도현", "박지후", "정민재", "최하린", "윤가람", "오준서"], owner: "박지후", status: "모집 중" }, { id: "e2", title: "축제 부스 안전 교육", date: "8월 18일 (화)", time: "15:40–16:20", location: "과학 2실", department: "기획부 · 체육부", description: "화기와 전기 기기를 사용하는 부스 운영자를 위한 사전 안전 교육입니다.", capacity: 18, participants: ["이도현", "정민재", "윤가람"], owner: "한미정", status: "모집 중" }, { id: "e3", title: "1학기 학생회 활동 기록 사진 정리", date: "8월 25일 (화)", time: "방과 후", location: "학생회실", department: "홍보부", description: "아카이브에 올릴 사진을 행사별로 분류합니다.", capacity: 8, participants: ["김서윤", "오준서"], owner: "김서윤", status: "예정" },
];
export const announcements: Announcement[] = [
  { id: "a1", title: "[중요] 축제 부스 운영표는 15일 오후 5시까지 확인해 주세요", body: "부서별로 담당 시간과 인원을 다시 확인해 주세요. 비어 있는 시간대는 기획부에 바로 알려 주면 운영표에 반영하겠습니다.", author: "박지후 · 학생회장", createdAt: "오늘 08:10", target: "학생회 전체", pinned: true, read: false }, { id: "a2", title: "학생회 후드 공동 구매 신청 안내", body: "희망자만 신청해 주세요. 사이즈 변경은 신청 마감 전까지 가능합니다.", author: "김서윤 · 홍보부", createdAt: "어제 17:20", target: "학생회 전체", pinned: false, read: false, application: { capacity: 45, applied: 31, deadline: "8월 17일 18:00" } }, { id: "a3", title: "8월 정기회의 안건을 올려 주세요", body: "회의 전날까지 안건을 회의록 메뉴에 남겨 주세요. 예산 관련 안건은 예상 금액도 함께 적어 주세요.", author: "한미정 · 담당 선생님", createdAt: "8월 12일", target: "부장단 · 회장단", pinned: false, read: true }, { id: "a4", title: "교내 방송 장비 사용 전 확인 사항", body: "사용 후에는 마이크 전원을 끄고 케이블을 정리해 주세요.", author: "이도현 · 기획부장", createdAt: "8월 11일", target: "홍보부", pinned: false, read: true },
];
export const attendance: AttendanceRecord[] = [{ userId: "u1", name: "김서윤", department: "홍보부", status: "ATTEND" }, { userId: "u2", name: "이도현", department: "기획부", status: "ATTEND" }, { userId: "u3", name: "박지후", department: "회장단", status: "LATE" }, { userId: "u5", name: "정민재", department: "체육부", status: "ATTEND" }, { userId: "u6", name: "최하린", department: "생활안전부", status: "ABSENT" }, { userId: "u7", name: "윤가람", department: "기획부", status: "ATTEND" }, { userId: "u8", name: "오준서", department: "홍보부", status: "EXCUSED" }];
export const teams: Team[] = [{ id: "g1", name: "축제 안내팀", purpose: "입구 안내와 미아 발생 시 연락", members: ["김서윤", "최하린", "오준서"], memberIds: ["u1", "u6", "u8"], leader: "김서윤", leaderId: "u1" }, { id: "g2", name: "무대 진행팀", purpose: "공연 순서와 대기 안내", members: ["이도현", "윤가람"], memberIds: ["u2", "u7"], leader: "이도현", leaderId: "u2" }, { id: "g3", name: "체육대회 응원팀", purpose: "응원 도구 배부와 회수", members: ["정민재", "박지후"], memberIds: ["u5", "u3"], leader: "정민재", leaderId: "u5" }];
export const meetings: Meeting[] = [{ id: "m1", title: "8월 2주차 부장단 회의", date: "2026. 08. 12.", author: "이도현", summary: "축제 부스 운영표의 빈 시간대를 15일까지 취합하고, 후드 공동 구매는 공지로 다시 안내하기로 했습니다.", attachments: ["8월2주_회의자료.pdf", "부스운영표_초안.xlsx"] }, { id: "m2", title: "2학기 첫 학생회 정기회의", date: "2026. 08. 05.", author: "박지후", summary: "행사 일정과 부서별 이번 달 업무를 공유했습니다. 다음 회의는 워크숍 뒤에 진행합니다.", attachments: ["2학기_행사일정.pdf"] }];
export const notices: Notice[] = [{ id: "n1", title: "마감 하루 전이에요", body: "‘학교 축제 부스 운영표 확인’ 업무가 내일 오후 5시에 마감됩니다.", time: "12분 전", read: false, link: "/tasks/t1" }, { id: "n2", title: "새 공지가 올라왔어요", body: "학생회 후드 공동 구매 신청 안내를 확인해 주세요.", time: "오늘 08:12", read: false, link: "/announcements" }, { id: "n3", title: "업무가 완료됐어요", body: "학생회실 물품 정리 사진이 제출되어 업무가 완료됐습니다.", time: "어제", read: true, link: "/tasks/t7" }];
export const archives: Archive[] = [{ id: "ar1", semester: "2026학년도 1학기", name: "제18대 학생회", members: 28, note: "축제·체육대회·환경 캠페인 기록 42건", locked: true }, { id: "ar2", semester: "2025학년도 2학기", name: "제17대 학생회", members: 26, note: "학기말 발표회와 나눔장터 기록 35건", locked: true }, { id: "ar3", semester: "2025학년도 1학기", name: "제17대 학생회", members: 25, note: "학교폭력 예방 캠페인 자료 포함", locked: true }];
