/** StudentFlow | 학기 운영 보드: 한 손으로 연속 변경할 수 있는 큰 상태 버튼과 저장 확인을 쓴다 */
import { CheckCircle2, ClipboardCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { useApp } from "@/contexts/AppContext";
import type { AttendanceStatus } from "@/types";
import { Button, PermissionState, StatusBadge } from "@/components/primitives";

const options: Array<{ value: AttendanceStatus; label: string }> = [{ value: "ATTEND", label: "출석" }, { value: "LATE", label: "지각" }, { value: "ABSENT", label: "결석" }, { value: "EXCUSED", label: "인정" }];
const statusLabel: Record<AttendanceStatus, string> = { ATTEND: "출석", LATE: "지각", ABSENT: "결석", EXCUSED: "인정" };

export default function AttendancePage() {
  const { attendance, currentRole, setAttendanceStatus, saveAttendance } = useApp();
  const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  const canEdit = ["EXECUTIVE_BOARD", "TEACHER"].includes(currentRole);
  const count = useMemo(() => attendance.reduce((acc, item) => ({ ...acc, [item.status]: (acc[item.status] ?? 0) + 1 }), {} as Record<string, number>), [attendance]);
  async function save() { setSaving(true); setSaved(false); await saveAttendance(); setSaving(false); setSaved(true); }
  return <div className="mx-auto max-w-[1080px] px-4 py-7 sm:px-6 lg:px-8"><header className="mb-6"><p className="text-sm text-slate-500">출석</p><h1 className="mt-1 text-2xl font-bold tracking-[-.03em]">여름 워크숍 출석</h1><p className="mt-2 text-sm text-slate-500">2026년 8월 14일 · 시청각실 · 총 {attendance.length}명</p></header><section className="grid grid-cols-2 border border-slate-200 bg-white sm:grid-cols-4">{options.map((option) => <div key={option.value} className="border-b border-r border-slate-200 p-4 sm:border-b-0"><p className="text-xs font-bold text-slate-500">{option.label}</p><p className="mt-1 text-2xl font-bold text-slate-800">{count[option.value] ?? 0}</p></div>)}</section>{!canEdit ? <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_300px]"><section className="border border-slate-200 bg-white"><div className="border-b border-slate-200 px-4 py-3"><h2 className="font-bold">현재 출석 현황</h2></div><div className="divide-y divide-slate-100">{attendance.map((record) => <div key={record.userId} className="flex items-center justify-between px-4 py-3"><div><p className="text-sm font-semibold text-slate-800">{record.name}</p><p className="mt-0.5 text-xs text-slate-500">{record.department}</p></div><StatusBadge label={statusLabel[record.status]}/></div>)}</div></section><PermissionState title="출석 변경은 회장단과 담당 선생님만 할 수 있어요." description="현재 역할에서는 출석 현황만 확인할 수 있어요."/></div> : <><section className="mt-5 overflow-hidden border border-slate-200 bg-white"><div className="divide-y divide-slate-100">{attendance.map((record) => <div key={record.userId} className="flex flex-col gap-3 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-slate-100 text-xs font-bold text-slate-600">{record.name[0]}</span><div><p className="text-sm font-bold text-slate-800">{record.name}</p><p className="mt-0.5 text-xs text-slate-500">{record.department}</p></div></div><div className="flex flex-wrap gap-1.5" role="group" aria-label={`${record.name} 출석 상태`}>{options.map((option) => <button key={option.value} onClick={() => { setAttendanceStatus(record.userId, option.value); setSaved(false); }} className={`min-h-10 rounded border px-3 text-sm font-semibold transition ${record.status === option.value ? "border-[#2563a8] bg-[#e8f0f8] text-[#1f528b]" : "border-slate-200 bg-white text-slate-500 hover:bg-slate-50"}`}>{option.label}</button>)}</div></div>)}</div></section><div className="sticky bottom-16 mt-5 flex flex-wrap items-center justify-between gap-3 border border-slate-200 bg-white p-3 shadow-sm lg:bottom-4"><div>{saved ? <p className="flex items-center gap-1.5 text-sm font-semibold text-[#17663d]"><CheckCircle2 size={17}/>출석 변경 내용을 저장했어요.</p> : <p className="text-sm text-slate-500">변경한 출석 상태를 저장해 주세요.</p>}</div><Button onClick={save} disabled={saving}>{saving ? "저장하는 중…" : "출석 저장하기"}<ClipboardCheck size={17}/></Button></div></>}</div>;
}
