/** StudentFlow | 학기 운영 보드: 페이지가 아닌 하나의 컨텍스트에서 데모 상태와 액션을 관리 */
import { studentflowApi } from "@/lib/api";
import { announcements as initialAnnouncements, archives, attendance as initialAttendance, events as initialEvents, meetings as initialMeetings, notices as initialNotices, submissions as initialSubmissions, tasks as initialTasks, teams as initialTeams, users as initialUsers } from "@/lib/sample-data";
import type { Announcement, AttendanceRecord, AttendanceStatus, EventItem, Meeting, Notice, Role, Submission, SubmissionStatus, Task, TaskStatus, Team, User } from "@/types";
import { createContext, useContext, useMemo, useState, type ReactNode } from "react";
type AppContextValue = { signedIn: boolean; currentRole: Role; currentUser: User; users: User[]; tasks: Task[]; submissions: Submission[]; events: EventItem[]; announcements: Announcement[]; attendance: AttendanceRecord[]; teams: Team[]; meetings: Meeting[]; notices: Notice[]; archives: typeof archives; signIn: (role: Role) => Promise<boolean>; signOut: () => void; setRole: (role: Role) => void; createTask: (input: Pick<Task, "title" | "description" | "department" | "dueDate" | "priority">) => void; updateTask: (taskId: string, input: Pick<Task, "title" | "description">) => void; updateTaskStatus: (taskId: string, status: TaskStatus) => void; submitTask: (taskId: string, fileName: string) => Promise<void>; reviewSubmission: (submissionId: string, status: Extract<SubmissionStatus, "APPROVED" | "REJECTED">, feedback?: string) => Promise<void>; publishAnnouncement: (input: Pick<Announcement, "title" | "body" | "target">) => void; toggleEventJoin: (eventId: string) => void; setAttendanceStatus: (userId: string, status: AttendanceStatus) => void; saveAttendance: () => Promise<void>; moveTeamMember: (fromTeamId: string, toTeamId: string, member: string) => void; createMeeting: (input: Pick<Meeting, "title" | "date" | "summary"> & { attachment?: string }) => void; markNoticeRead: (id: string) => void; markAllNoticesRead: () => void; changeUserRole: (userId: string, role: Role) => void; };
const AppContext = createContext<AppContextValue | null>(null);
export function AppProvider({ children }: { children: ReactNode }) { const [signedIn, setSignedIn] = useState(() => new URLSearchParams(window.location.search).get("demo") === "1"); const [currentRole, setCurrentRole] = useState<Role>(() => { const role = new URLSearchParams(window.location.search).get("role"); return role === "DEPARTMENT_HEAD" || role === "EXECUTIVE_BOARD" || role === "TEACHER" ? role : "MEMBER"; }); const [users, setUsers] = useState(initialUsers); const [tasks, setTasks] = useState(initialTasks); const [submissions, setSubmissions] = useState(initialSubmissions); const [events, setEvents] = useState(initialEvents); const [announcements, setAnnouncements] = useState(initialAnnouncements); const [attendance, setAttendance] = useState(initialAttendance); const [teams, setTeams] = useState(initialTeams); const [meetings, setMeetings] = useState(initialMeetings); const [notices, setNotices] = useState(initialNotices);
  const currentUser = useMemo(() => users.find((user) => user.role === currentRole) ?? users[0], [currentRole, users]);
  const value: AppContextValue = { signedIn, currentRole, currentUser, users, tasks, submissions, events, announcements, attendance, teams, meetings, notices, archives,
    async signIn(role) { const result = await studentflowApi.auth.signIn(); if (result.ok) { setCurrentRole(role); setSignedIn(true); } return result.ok; }, signOut() { setSignedIn(false); }, setRole: setCurrentRole,
    createTask(input) { setTasks((previous) => [{ id: `t${Date.now()}`, assigneeId: currentUser.id, status: "TODO", submitted: false, ...input }, ...previous]); },
    updateTask(taskId, input) { setTasks((previous) => previous.map((task) => task.id === taskId ? { ...task, ...input } : task)); },
    updateTaskStatus(taskId, status) { setTasks((previous) => previous.map((task) => task.id === taskId ? { ...task, status } : task)); },
    async submitTask(taskId, fileName) { await studentflowApi.tasks.save(); const task = tasks.find((item) => item.id === taskId); setTasks((previous) => previous.map((item) => item.id === taskId ? { ...item, submitted: true, status: "IN_REVIEW" } : item)); setSubmissions((previous) => [{ id: `s${Date.now()}`, taskId, studentName: currentUser.name, taskTitle: task?.title ?? "제출한 업무", fileName, submittedAt: "방금 전", status: "PENDING" }, ...previous]); },
    async reviewSubmission(submissionId, status, feedback) { await studentflowApi.tasks.save(); const submission = submissions.find((item) => item.id === submissionId); setSubmissions((previous) => previous.map((item) => item.id === submissionId ? { ...item, status, reviewer: currentUser.name, feedback } : item)); if (submission) setTasks((previous) => previous.map((task) => task.id === submission.taskId ? { ...task, status: status === "APPROVED" ? "DONE" : "REJECTED" } : task)); },
    publishAnnouncement(input) { setAnnouncements((previous) => [{ id: `a${Date.now()}`, author: `${currentUser.name} · ${currentUser.department}`, createdAt: "방금 전", pinned: false, read: true, ...input }, ...previous]); },
    toggleEventJoin(eventId) { setEvents((previous) => previous.map((event) => event.id !== eventId ? event : { ...event, participants: event.participants.includes(currentUser.name) ? event.participants.filter((name) => name !== currentUser.name) : [...event.participants, currentUser.name] })); },
    setAttendanceStatus(userId, status) { setAttendance((previous) => previous.map((record) => record.userId === userId ? { ...record, status } : record)); }, async saveAttendance() { await studentflowApi.attendance.save(); },
    moveTeamMember(fromTeamId, toTeamId, member) { if (fromTeamId === toTeamId) return; setTeams((previous) => previous.map((team) => team.id === fromTeamId ? { ...team, members: team.members.filter((name) => name !== member) } : team.id === toTeamId ? { ...team, members: [...team.members, member] } : team)); },
    createMeeting(input) { setMeetings((previous) => [{ id: `m${Date.now()}`, author: currentUser.name, attachments: input.attachment ? [input.attachment] : [], ...input }, ...previous]); }, markNoticeRead(id) { setNotices((previous) => previous.map((notice) => notice.id === id ? { ...notice, read: true } : notice)); }, markAllNoticesRead() { setNotices((previous) => previous.map((notice) => ({ ...notice, read: true }))); }, changeUserRole(userId, role) { setUsers((previous) => previous.map((user) => user.id === userId ? { ...user, role } : user)); }, };
  return <AppContext.Provider value={value}>{children}</AppContext.Provider>; }
export function useApp() { const context = useContext(AppContext); if (!context) throw new Error("useApp은 AppProvider 안에서 사용해야 합니다."); return context; }
